# This Dockerfile was helpful for building and packaging dserv, essctrl, essgui, and TCL 9.
# Docker gives a clean environment, meaning the steps below must account for all dependencies.
# Docker also gives us a local environment that's easy to iterate on.
# Getting this working was the basis for the automated CI builds, over in .github/workflows/.
#
# To run this docker build and produce a Docker image, cd to the dserv repo root and:
#
#   docker build . -f scripts/docker/Dockerfile-package -t dserv-package:local
#
# To grab the generated .deb package out of a container from this image:
#
#   docker run --rm -ti -v $PWD:$PWD dserv-package:local cp /work/dserv-test.deb $PWD
#
# To test package installation and running programs, see scripts/docker/Dockerfile-run.

# Start with a fresh Ubuntu environment.
FROM ubuntu:22.04

# Install build tools, dserv build dependencies, and essgui build dependencies.
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt update \
    && apt install --no-install-recommends --yes git wget ca-certificates build-essential cmake zip unzip \
    libevdev-dev zlib1g-dev \
    libpango1.0-dev libwayland-dev wayland-protocols libxkbcommon-dev libxinerama-dev libdbus-1-dev libglew-dev  libdecor-0-dev libgtk-3-dev liblz4-dev \
    && apt-get clean \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*

# Install TLC 9 into the build environment, and to a packaging dir.
WORKDIR /work
RUN git clone --depth=1 --branch core-9-0-1-rc https://github.com/tcltk/tcl.git \
  && cd tcl/unix/ \
  && ./configure --prefix=/work/package/usr/local/ \
  && make \
  && make install \
  && ./configure \
  && make \
  && make install

# Install Jansson JSON library into the build environment.
WORKDIR /work
RUN git clone https://github.com/akheron/jansson.git \
  && cd jansson/ \
  && git checkout v2.14 \
  && cmake -B build \
  && cmake --build build \
  && cmake --install build

# Install FLTK GUI framework into the build environment.
WORKDIR /work
RUN git clone https://github.com/fltk/fltk.git \
  && cd fltk \
  && git checkout release-1.4.2 \
  && cmake -B build \
  && cmake --build build \
  && cmake --install build  

# Install libharu PDF library into the build environment.
WORKDIR /work
RUN git clone https://github.com/libharu/libharu.git \
  && cd libharu \
  && git checkout v2.4.4 \
  && cmake -DBUILD_SHARED_LIBS=OFF -B build \
  && cmake --build build \
  && cmake --install build

# Install our dlsh libs and headers into the build environment.
ENV DLSH_VERSION=0.0.13
WORKDIR /work/dlsh
RUN wget https://github.com/benjamin-heasly/dlsh/releases/download/$DLSH_VERSION/dlsh-Linux-$(dpkg --print-architecture)-$DLSH_VERSION.zip \
  && unzip dlsh-Linux-$(dpkg --print-architecture)-$DLSH_VERSION.zip \
  && cp ./lib/*.a /usr/local/lib \
  && cp ./lib/*.so /usr/local/lib \
  && cp ./include/*.h /usr/local/include

# Install our dlsh TCL utils and thier dependencies into the packaging dir.
WORKDIR /work/package/usr/local/dlsh
RUN wget https://github.com/benjamin-heasly/dlsh/releases/download/initial/dlsh.zip

# Build dserv itself and install to the packaging dir.
ADD . /work/dserv
WORKDIR /work/dserv/
RUN cmake -DCMAKE_INSTALL_PREFIX=/work/package/usr/local -B build \
  && cmake --build build \
  && cmake --install build

# Build essgui itself and install to the packaging dir.
WORKDIR /work/dserv/tools/essgui
RUN cmake -DCMAKE_INSTALL_PREFIX=/work/package/usr/local -B build \
  && cmake --build build \
  && cmake --install build

# Add metadata and scripts for the .deb package.
WORKDIR /work/package/DEBIAN
RUN cp /work/dserv/dpkg/control . \
  && echo "Version: 0.0.test" >> ./control \
  && echo "Architecture: $(dpkg --print-architecture)" >> ./control \
  && cp /work/dserv/dpkg/postinst . \
  && chmod +x ./postinst \
  && cp /work/dserv/dpkg/install-dserv-service.sh . \
  && chmod +x ./install-dserv-service.sh

# Build the .deb package.
WORKDIR /work
RUN dpkg-deb --build /work/package dserv-test.deb
