# This Dockerfile was helpful for building and packaging essgui.
# Docker gives a clean environment, meaning the steps below must account for all dependencies.
# Docker also gives us a local environment that's easy to iterate on.
# Getting this working was the basis for the automated CI builds, over in .github/workflows/.
#
# To run this docker build and produce a Docker image, cd to the dserv repo root and:
#
#   docker build . -f scripts/docker/Dockerfile-essgui-package -t essgui-package:local
#
# To sanity check the packaged artifact:
#
#   docker run --rm -ti essgui-package:local dpkg-deb --info essgui_0.0.0_amd64.deb
#   docker run --rm -ti essgui-package:local dpkg-deb --contents essgui_0.0.0_amd64.deb
#
# To grab the generated .deb package out of a container from this image:
#
#   docker run --rm -ti -v $PWD:$PWD essgui-package:local cp essgui_0.0.0_amd64.deb $PWD
#
# To test package installation and running programs, see scripts/docker/Dockerfile-essgui-run.

# Start with a fresh Ubuntu environment.
FROM ubuntu:22.04

# Install build tools and essgui build dependencies.
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt update \
    && apt install --no-install-recommends --yes wget ca-certificates build-essential cmake zip unzip \
    libpango1.0-dev libwayland-dev wayland-protocols libxkbcommon-dev libxinerama-dev libdbus-1-dev libglew-dev  libdecor-0-dev libgtk-3-dev liblz4-dev \
    && apt-get clean \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*

# Add this repo and submodules.
ADD . /work/dserv/

# Install TLC 9 into the build environment.
WORKDIR /work/dserv/deps/tcl/unix
RUN ./configure \
  && make \
  && make install

# Install Jansson JSON library into the build environment.
WORKDIR /work
RUN git clone https://github.com/akheron/jansson.git \
  && cd jansson/ \
  && git checkout v2.14 \
  && cmake -B build \
  && cmake --build build \
  && cmake --install build

# Install FLTK GUI framework into the build environment.
WORKDIR /work
RUN git clone https://github.com/fltk/fltk.git \
  && cd fltk \
  && git checkout release-1.4.2 \
  && cmake -B build \
  && cmake --build build \
  && cmake --install build  

# Install libharu PDF library into the build environment.
WORKDIR /work
RUN git clone https://github.com/libharu/libharu.git \
  && cd libharu \
  && git checkout v2.4.4 \
  && cmake -DBUILD_SHARED_LIBS=OFF -B build \
  && cmake --build build \
  && cmake --install build

# Install our dlsh libs and headers into the build environment.
ENV DLSH_VERSION=0.0.15
WORKDIR /work/dlsh
RUN wget https://github.com/benjamin-heasly/dlsh/releases/download/${DLSH_VERSION}/dlsh_${DLSH_VERSION}_amd64.deb \
  && dpkg --install dlsh_${DLSH_VERSION}_amd64.deb

# Build essgui itself and package it for release.
ADD . /work/dserv
WORKDIR /work/dserv/tools/essgui
RUN cmake -D PROJECT_VERSION=0.0.0 -B build \
  && cmake --build build \
  && cpack -G DEB --config build/CPackConfig.cmake
