# This Dockerfile was helpful for testing packaged dserv, essctrl, and essgui.
# Docker gives a clean environment, meaning the steps below must account for all dependencies.
# Docker also gives us a local environment that's easy to iterate on.
# Getting this working was the basis for the automated CI builds, over in .github/workflows/.
#
# This assumes we already have a .deb package containing dserv, essctrl, and essgui.
# You can make this locally using scripts/docker/Dockerfile-dserv-package.
# Or, you can get a package from a GitHub release:
#
#   wget https://github.com/benjamin-heasly/dserv/releases/download/0.0.33/dserv-Linux-amd64-0.0.33.deb
#   mv dserv-Linux-amd64-0.0.33.deb dserv_0.0.0_amd64.deb
#
# To install the package in a fresh Docker image:
#
#   docker build . --no-cache -f scripts/docker/Dockerfile-dserv-run -t dserv-run:local
#
# To test the installed dserv:
#
#   docker run --rm -ti dserv-run:local /usr/local/dserv/dserv --help
#   docker run --rm -ti dserv-run:local timeout --signal SIGINT 2 /usr/local/dserv/dserv -c /usr/local/dserv/config/dsconf.tcl -t /usr/local/dserv/config/triggers.tcl
#
# To test the installed essctrl:
#
#   docker run --rm -ti dserv-run:local /bin/sh -c 'echo "test" | essctrl && cat history.txt'
#
# To sanity check some installed / configured directories:
#
#   docker run --rm -ti dserv-run:local ls -alth /usr/local/bin
#   docker run --rm -ti dserv-run:local ls -alth /usr/local/dserv/db

# Start with a fresh Ubuntu environment.
FROM ubuntu:22.04

# Install the .deb package built elsewhere into this fresh environment.
# Using apt to install it means we'll also install runtime dependencies declared in the dpkg/control file.
WORKDIR /opt
ADD dserv_0.0.0_amd64.deb .
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt update \
    && apt install --no-install-recommends --yes wget ca-certificates /opt/dserv_0.0.0_amd64.deb \
    && apt-get clean \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*

# Install our dlsh TCL utils and their dependencies.
WORKDIR /usr/local/dlsh
RUN wget https://github.com/benjamin-heasly/dlsh/releases/download/initial/dlsh.zip
