# gen_box_version.cmake -- write box_version.h with this tree's `git describe`.
#
# Run as a build STEP, not at configure time, and that is the whole point: a
# version computed when CMake last ran is a version that goes stale the moment
# you commit, and a box would then report -- with complete confidence -- an
# image it is not running. Reporting the wrong version is worse than reporting
# none, because "up to date" is a conclusion someone acts on.
#
# The string must match publish.sh's, since the shelf keys its versions off the
# same command: `git describe --tags --always --dirty`.
#
# Writes only when the content CHANGES, so an unchanged tree does not relink the
# whole image on every build.

execute_process(
  COMMAND git describe --tags --always --dirty
  WORKING_DIRECTORY "${SRC_DIR}"
  OUTPUT_VARIABLE ver
  OUTPUT_STRIP_TRAILING_WHITESPACE
  ERROR_QUIET
)
if(NOT ver)
  # A source tree with no git (a release tarball, a CI checkout without history)
  # must still build. "unknown" is honest and compares equal to nothing.
  set(ver "unknown")
endif()

set(content "/* generated by cmake/gen_box_version.cmake -- do not edit */\n#define BOX_VERSION \"${ver}\"\n")
if(EXISTS "${OUT}")
  file(READ "${OUT}" old)
  if(old STREQUAL content)
    return()
  endif()
endif()
get_filename_component(dir "${OUT}" DIRECTORY)
file(MAKE_DIRECTORY "${dir}")
file(WRITE "${OUT}" "${content}")
