#!/bin/sh
# host_gpio_rtt.sh -- host-GPIO edge -> extio box DI arrival, measured in dserv,
# with an OPTIONAL same-edge native-GPIO baseline for a true A/B.
#
# This is the one-way INPUT path, the number that matters for behavioral events
# (subject presses a button -> dserv knows):
#
#   RT_box  = [now]@arrival(<dev>/state/di/<ipin>)  -  [now]@host ioctl
#           = ioctl -> wire -> box senses DI -> (debounce) -> frame -> USB -> dserv
#
# Unlike loopback_rtt.sh (box DO -> box DI, the FULL closed loop) the box's
# output path is not in this measurement -- the edge is generated by the host's
# own GPIO, so what is left is purely "how fast does an input reach dserv".
#
# Tee the same wire into a spare host INPUT line and you get the comparison the
# whole exercise is about, off the identical physical edge and the identical t0:
#
#   RT_host = [now]@arrival(gpio/input/<hpin>) - [now]@host ioctl   (native RP1)
#   RT_box  = same edge, via the box and USB
#
# t0 comes from gpio/output/<opin>, which gpio_output.c publishes on every drive
# (stamped in C immediately after the ioctl returns). So this reads exactly like
# loopback_rtt does off cmd/do/<n> -- no [now] bracketing in Tcl, and no
# interpreter latency folded into the measurement.
#
# Because t0 is stamped just AFTER the ioctl, it is a hair later than the real
# edge, which makes RT a slight UNDER-estimate. The bias is one syscall return.
#
# TWO INTERPS: the gpio* commands are loaded into the `ess` subprocess
# (config/essconf.tcl), not the main interp -- drive the line with `dservctl ess`.
# Datapoint reads work from either, so the captures use the main interp.
# Note also that tclserver_set_point is ASYNC: a datapoint is not readable in the
# same script that sets it, which is why the drive and the read are separate calls.
#
# CAVEAT on the baseline: gpio_input.c stamps events with tclserver_now(), NOT
# the kernel's gpio_v2_line_event.timestamp_ns (read and left commented out). So
# RT_host is "when dserv learned about the edge", including thread wakeup and
# publish -- the same layer at which RT_box is stamped. Fair A/B, but neither
# number is a hardware-edge measurement.
#
# WIRING (Raspberry Pi 5 + Teensy 4.0 box; all 3.3 V, Teensy is NOT 5 V tolerant)
#   Pi phys 13 (GPIO27) --+-- Teensy pin 7   = B1_01 = gpio2.17 = box DI 17
#                         +-- Pi phys 15 (GPIO22)        [optional baseline]
#   Pi phys 14 (GND)  ------- Teensy GND
#
# BOX SETUP first, else no samples / inflated ones:
#   pin 17 mode in            (or in_pullup)
#   pin 17 debounce 0         <-- CRITICAL: a 25 ms debounce dominates every sample
# remotely:  dservctl -c 'dservSet extio/box/config/pin/17/mode 2'
#
# NOTE box pin n IS gpio2 bit n on a Teensy 4.x (box_gpio.c off_of() is flat), and
# only some gpio2 bits reach a pad on a 4.0: 0,1,2,3 -> T10,T12,T11,T13(LED);
# 10,11 -> T6,T9;  16,17 -> T8,T7;  12,18,19,28,29 -> T32,T36,T37,T35,T34 (bottom).
# Bits 4-9, 13-15, 20-27, 30, 31 are LPI2C2 / ENET-PHY / RMII silicon -- no pad.
#
#   sh host_gpio_rtt.sh <extio/name> [ipin] [opin] [iters] [hpin]
#   sh host_gpio_rtt.sh extio/box 17 27 500        # box path only
#   sh host_gpio_rtt.sh extio/box 17 27 500 22     # + native baseline
#   (box name: `dservctl -c 'dservGet extio/boxes'`)
DEV=${1:?usage: host_gpio_rtt.sh <extio/name> [ipin] [opin] [iters] [hpin]}
IPIN=${2:-17}
OPIN=${3:-27}
N=${4:-500}
HPIN=${5:-}
SETTLE=0.02
OUT=/tmp/host_gpio_rtt.txt

if [ -n "$HPIN" ]; then
  echo "host-GPIO RTT: GPIO$OPIN -> $DEV/state/di/$IPIN   + baseline gpio/input/$HPIN   n=$N"
else
  echo "host-GPIO RTT: GPIO$OPIN -> $DEV/state/di/$IPIN   n=$N"
fi
echo "------------------------------------------------------------------"

# ---- WHICH QUANTITY AM I MEASURING? The box's sync state decides, so detect it
# rather than assume. main.c:487 stamps state/di/<n> with event_stamp(ev.t_us) ->
# box_clock_stamp(), which returns 0 (=> dserv stamps on ARRIVAL) until the first
# obs anchor lands, and the box's own mapped EDGE time after that. Same wire, same
# script, two different quantities:
#
#   unsynced -> DELIVERY  : t_arrival - t_ioctl. How long until dserv knows. This
#                           is what gates an ESS state advance or a juice pulse.
#   synced   -> ACCURACY  : t_boxedge_mapped - t_ioctl. The edge physically occurs
#                           ~1 us after the ioctl, so this is the box clock's
#                           mapping error against the host's clock, measured
#                           against real hardware. CAN BE NEGATIVE (box clock
#                           ahead), which is signal, not an outlier -- so the
#                           sample filter below keys on "did an event arrive",
#                           not on the sign of the difference.
#
# Both are worth having. Reboot the box (no beginobs since) to get DELIVERY.
# Both are captured every sample, because they are independent and a box can be
# excellent at one while bad at the other:
#
#   DELIVERY = [now] taken in the arrival callback  - t_ioctl
#   STAMP    = dservTimestamp <dev>/state/di/<n>    - t_ioctl
#
# The callback's [now] is arrival/execution time and is INDEPENDENT of whatever
# timestamp the frame carried -- so capturing only that (an earlier version of
# this script) silently measures delivery no matter what the box's clock is
# doing. Reading the datapoint's own timestamp is the only way to see the stamp.
#
# Do NOT try to infer the mode from state/sync/offset_us: that datapoint is
# STICKY in dserv's table, so it reports "this box synced at some point", not
# "this box is synced now". It survives box reboots.

# ---- setup: capture procs live in whatever interp the dpoint script runs in,
# so arrival is signalled through DATAPOINTS, never Tcl vars (see loopback_rtt.tcl)
dservctl -c "proc __hg_box {args} { dservSet test/hg_box [now] }
dservAddExactMatch $DEV/state/di/$IPIN
dpointSetScript $DEV/state/di/$IPIN __hg_box" >/dev/null \
  || { echo "  setup failed -- is dserv up?"; exit 1; }

# gpio* commands live in the `ess` subprocess interp, not the main one
dservctl ess "gpioLineRequestOutput $OPIN 0" >/dev/null \
  || { echo "  gpioLineRequestOutput failed -- gpioOutputInit not done in ess?"; exit 1; }
if [ -n "$HPIN" ]; then
  dservctl -c "proc __hg_host {args} { dservSet test/hg_host [now] }
dservAddExactMatch gpio/input/$HPIN
dpointSetScript gpio/input/$HPIN __hg_host" >/dev/null
  dservctl ess "gpioLineRequestInput $HPIN BOTH 0 PULL_NONE ACTIVE_HIGH" >/dev/null
fi

: > "$OUT"
i=0
while [ "$i" -lt "$N" ]; do
  dservctl -c "dservSet test/hg_box 0
dservSet test/hg_host 0" >/dev/null
  dservctl ess "gpioLineSetValue $OPIN $((i % 2))" >/dev/null
  sleep "$SETTLE"
  # every read is catch-guarded: dservTimestamp/dservGet THROW on a datapoint that
  # does not exist yet, and state/di/<n> does not exist until the first edge -- an
  # unguarded read makes the whole script fail on iteration 1 of a fresh box
  R=$(dservctl -c "set a 0; catch {set a [dservTimestamp gpio/output/$OPIN]}
set b 0; catch {set b [dservGet test/hg_box]}
set c 0; catch {set c [dservTimestamp $DEV/state/di/$IPIN]}
set d 0; catch {set d [dservGet test/hg_host]}
list \$a \$b \$c \$d" 2>/dev/null)
  set -- $R
  T0=${1:-0}; AB=${2:-0}; SB=${3:-0}; AH=${4:-0}
  RB=$((AB - T0)); RS=$((SB - T0)); RH=$((AH - T0))
  # keyed on "an event arrived" (AB != 0), never on sign: the STAMP column is
  # routinely negative (box clock behind dserv), and that is the measurement
  if [ "$AB" -ne 0 ] && [ "$T0" -ne 0 ] && [ "$RB" -lt 500000 ] && [ "$RB" -gt 0 ]; then
    if [ -n "$HPIN" ] && [ "$AH" -ne 0 ]; then
      echo "$RB $RS $RH" >> "$OUT"
    elif [ -z "$HPIN" ]; then
      echo "$RB $RS -" >> "$OUT"
    fi
  fi
  i=$((i + 1))
done

dservctl -c "catch {dpointRemoveScript $DEV/state/di/$IPIN}
catch {dservRemoveMatch $DEV/state/di/$IPIN}
catch {dpointRemoveScript gpio/input/$HPIN}
catch {dservClear test/hg_box}
catch {dservClear test/hg_host}" >/dev/null

# leave the output line LOW so a re-run starts from a known level
dservctl ess "catch {gpioLineSetValue $OPIN 0}" >/dev/null

# sort the column outside awk -- mawk (Debian default) has no asort()
summarize() {   # $1 = column, $2 = label
  awk -v col="$1" '$col != "-" { print $col }' "$OUT" | sort -n | awk -v lbl="$2" '{v[NR]=$1; s+=$1}
    END{ n=NR; if(n<2){ printf "  %-18s (insufficient samples)\n", lbl; exit }
      printf "  %-18s min %6d  med %6d  p90 %6d  p99 %6d  max %7d  mean %6.0f us  (n=%d)\n",
             lbl, v[1], v[int(n/2)+1], v[int(n*0.9)+1], v[int(n*0.99)+1], v[n], s/n, n; }'
}

summarize 1 "delivery (USB)"
summarize 2 "box stamp error"
[ -n "$HPIN" ] && summarize 3 "delivery (native)"
echo "------------------------------------------------------------------"
echo "delivery      = when dserv LEARNED. Gates ESS state advances / juice."
echo "                min is the floor, p99/max the jitter a rig actually feels."
echo "stamp error   = box's mapped edge time vs the host's. Negative = box clock"
echo "                behind. The SPREAD is sync quality; the MEDIAN is standing"
echo "                bias, which grows with time since the last obs anchor when"
echo "                no rate correction has been learned (state/sync/rate_ppb)."
[ -s "$OUT" ] || echo "  NO SAMPLES -- check: wire GPIO$OPIN -> T7, box 'pin $IPIN mode in', 'pin $IPIN debounce 0'"
