/*
 * pico_status_led.h -- the handheld's one-pixel status indicator.
 *
 * The SparkFun Thing Plus RP2350 carries a single WS2812 on GP14
 * (PICO_DEFAULT_WS2812_PIN, board header) and NO other display, so this LED is
 * the handheld's entire local UI: a glance tells you whether it is searching,
 * linked+secure, or in trouble -- without a console or the fleet page. Compiled
 * in ONLY for the thingplus-handheld target (BOX_STATUS_LED, set in build.sh);
 * the plain pico2_w bench handheld has no WS2812, so the pin/PIO cost never
 * lands there.
 *
 * PLACEMENT: core 0 (the radio/console core). Driving a WS2812 is timing-
 * critical, so it goes through PIO -- one non-blocking FIFO push per color
 * CHANGE (the pixel latches and holds), never a per-loop bit-bang, and never
 * an IRQ-off window on the radio core. The caller computes a logical STATUS_*
 * each pass (it owns all the signals: box_ble_state/link, connection/encrypt,
 * battery %); this module owns only the color + the blink/blip animation.
 *
 * POWER: the good/searching states are brief BLIPS (tens of ms every 1.5-3 s),
 * dark the rest of the time, so the LED's average draw on the battery is ~uA --
 * in the same spirit as the peripheral-latency idle budget (BLE.md "Power").
 *
 * Rail note: on the Thing Plus the WS2812 (like the Qwiic/fuel-gauge rail) is
 * fed by the peripheral regulator gated by GP13 -- ENABLED by default (the fuel
 * gauge works out of the box), so we never touch GP13. Driving GP13 low would
 * kill this LED and the fuel gauge (BLE.md board notes); GP14 is reserved from
 * user pin-config in pico_gpio.h while BOX_STATUS_LED.
 */
#ifndef PICO_STATUS_LED_H
#define PICO_STATUS_LED_H

#ifdef BOX_STATUS_LED

#include <string.h>
#include <stdio.h>
#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "ws2812.pio.h"          /* generated by pico_generate_pio_header (CMakeLists) */

#ifndef STATUS_LED_PIN
#define STATUS_LED_PIN PICO_DEFAULT_WS2812_PIN   /* GP14 on the Thing Plus */
#endif

/* Logical states, priority high->low as evaluated by the caller. */
enum {
    STATUS_LED_OFF = 0,     /* dark                                            */
    STATUS_LED_FAIL,        /* radio init failed -- no transport (red, fast)   */
    STATUS_LED_BRINGUP,     /* radio coming up (dim white)                     */
    STATUS_LED_LOWBATT,     /* battery low (red, slow pulse)                   */
    STATUS_LED_OBS,         /* in an observation period (steady green -- follows the sync line) */
    STATUS_LED_GOOD,        /* linked + encrypted + streaming (green blip)     */
    STATUS_LED_CONNECTING,  /* central connected, pipe not yet up (amber)      */
    STATUS_LED_SEARCHING    /* advertising, no central (blue blip)             */
};

/* Global brightness scale (0..255), applied to every AUTO color -- a WS2812 in
 * the hand is bright, and green dominates perceptually. Default is deliberately
 * dim; tune live with `led bright <n>`. The raw `led <r> <g> <b>` test color is
 * NOT scaled (explicit values). Set on core 1, read on core 0 (benign stale). */
#ifndef STATUS_LED_SCALE_DEFAULT
#define STATUS_LED_SCALE_DEFAULT 48
#endif
static volatile uint8_t g_led_scale = STATUS_LED_SCALE_DEFAULT;

static inline uint32_t status_scale(uint32_t grb)
{
    uint32_t s = g_led_scale;
    uint32_t g = ((grb >> 16) & 0xff) * s / 255;
    uint32_t r = ((grb >>  8) & 0xff) * s / 255;
    uint32_t b = ( grb        & 0xff) * s / 255;
    return (g << 16) | (r << 8) | b;
}

/* GRB pack (WS2812 wire order is g,r,b MSB-first); kept dim -- it's held in a
 * hand, and dim also protects the battery. */
static inline uint32_t status_grb(uint8_t r, uint8_t g, uint8_t b)
{ return ((uint32_t) g << 16) | ((uint32_t) r << 8) | (uint32_t) b; }

#define STATUS_C_RED    status_grb(48, 0, 0)
#define STATUS_C_GREEN  status_grb(0, 48, 0)
#define STATUS_C_BLUE   status_grb(0, 0, 64)
#define STATUS_C_AMBER  status_grb(48, 18, 0)
#define STATUS_C_WHITE  status_grb(20, 20, 20)

static PIO      status_pio;
static uint     status_sm;
static int      status_ok;              /* PIO claim succeeded -> we may drive */
static uint32_t status_last_grb = 1;    /* != any real color -> first push always happens */

/* Bench override (`led` CLI, non-persisted): 0 = auto, 1 = forced OFF,
 * 2 = forced raw color in status_force_grb. Set on core 1 (cmd_exec), read on
 * core 0 (service) -- volatile, benign staleness (the g_wdt_gate pattern). */
static volatile uint8_t  status_override;
static volatile uint32_t status_force_grb;

static inline void status_put(uint32_t grb)
{
    if (!status_ok) return;
    /* FIFO is effectively always empty (we push only on change); guard anyway so
     * a stuck SM can never block the radio core. */
    if (!pio_sm_is_tx_fifo_full(status_pio, status_sm))
        pio_sm_put(status_pio, status_sm, grb << 8u);   /* 24-bit, MSB-first */
}

static inline void status_led_init(void)
{
    uint offset;
    /* Modern SDK helper: pick a free PIO+SM that can reach the pin, avoiding the
     * SM cyw43 already claimed. Fail-soft: no LED is never fatal. */
    status_ok = pio_claim_free_sm_and_add_program_for_gpio_range(
                    &ws2812_program, &status_pio, &status_sm, &offset, STATUS_LED_PIN, 1, true);
    if (!status_ok) { printf("status-led: no free PIO SM -- LED disabled\n"); return; }
    ws2812_program_init(status_pio, status_sm, offset, STATUS_LED_PIN, 800000, false);
    status_put(0);                      /* start dark */
}

/* Map (logical state, phase in ms) -> scaled color. Blips keep the duty cycle
 * low; the global brightness scale is applied here so a `led bright` change
 * re-renders on the next pass (the raw override path stays unscaled). */
static inline uint32_t status_led_color(uint8_t state, uint32_t now)
{
    uint32_t c;
    switch (state) {
    case STATUS_LED_FAIL:       c = (now % 300  < 150) ? STATUS_C_RED   : 0; break;   /* fast blink   */
    case STATUS_LED_BRINGUP:    c = STATUS_C_WHITE;                          break;   /* solid, brief */
    case STATUS_LED_LOWBATT:    c = (now % 2000 < 400) ? STATUS_C_RED   : 0; break;   /* slow pulse   */
    case STATUS_LED_OBS:        c = STATUS_C_GREEN;                          break;   /* steady: obs on */
    case STATUS_LED_GOOD:       c = (now % 3000 <  60) ? STATUS_C_GREEN : 0; break;   /* rare blip    */
    case STATUS_LED_CONNECTING: c = STATUS_C_AMBER;                          break;   /* solid        */
    case STATUS_LED_SEARCHING:  c = (now % 1500 <  80) ? STATUS_C_BLUE  : 0; break;   /* searching    */
    default:                    c = 0;                                       break;
    }
    return status_scale(c);
}

/* Call every core-0 pass with the caller-computed logical state. Pushes only
 * when the rendered color changes, so the cost is ~a compare when idle. */
static inline void status_led_service(uint8_t state)
{
    if (!status_ok) return;
    uint32_t grb;
    if      (status_override == 1) grb = 0;
    else if (status_override == 2) grb = status_force_grb;
    else                           grb = status_led_color(state, to_ms_since_boot(get_absolute_time()));
    if (grb != status_last_grb) { status_last_grb = grb; status_put(grb); }
}

/* `led` CLI (bench): auto | off | bright <n> | r g b (raw, for bring-up checks). */
static inline void status_led_cli(const char *arg)
{
    int r, g, b, n;
    if      (!strcmp(arg, "auto") || !strcmp(arg, "1")) { status_override = 0; printf("led: auto\n"); }
    else if (!strcmp(arg, "off")  || !strcmp(arg, "0")) { status_override = 1; printf("led: forced off\n"); }
    else if (sscanf(arg, "bright %d", &n) == 1) {
        if (n < 0) n = 0;
        if (n > 255) n = 255;
        g_led_scale = (uint8_t) n; printf("led: brightness scale = %d/255\n", n);
    }
    else if (sscanf(arg, "%d %d %d", &r, &g, &b) == 3) {
        status_override = 2; status_force_grb = status_grb((uint8_t) r, (uint8_t) g, (uint8_t) b);
        printf("led: forced rgb %d,%d,%d\n", r, g, b);
    } else {
        printf("led: %s (usage: led auto|off | led <r> <g> <b>)\n",
               status_override == 0 ? "auto" : status_override == 1 ? "off" : "forced");
    }
    /* No repush poke needed: status_led_service pushes whenever the rendered
     * color changes, and an override that changes the color will differ. */
}

#endif /* BOX_STATUS_LED */
#endif /* PICO_STATUS_LED_H */
