// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef essgui_h
#define essgui_h

#include <FL/Fl_Tree.H>

int eval(char *command, void *cbdata);
int stim_eval(char *command, void *cbdata);
void tree_cb(Fl_Tree*, void*);
int esscmd(std::string cmd, std::string &rstr);
int esscmd(std::string cmd);
int esscmd(char *cmd, std::string &rstr);
int esscmd(const char *cmd);
int set_host(void);
int add_host(const char *);
int set_subject(void);
int set_system(void);
int set_protocol(void);
int set_variant(void);
int reload_system(void);
int reload_protocol(void);
int reload_variant(void);
int save_settings(void);
int reset_settings(void);
void recenter_eye_position(void);
void update_eye_settings(Fl_Widget *, long);
void save_script_cb(Fl_Widget *, void *);
void set_branch_cb(Fl_Widget *, void *);
void push_script_cb(Fl_Widget *, void *);
void pull_script_cb(Fl_Widget *, void *);
void juice_button_cb(Fl_Widget *, void *);

class VirtualEye;
void virtual_eye_cb(VirtualEye *w, void *data);
void send_virtual_eye_data(int adc_x, int adc_y);
void send_virtual_touch_event(int x, int y, int event_type);

class VirtualJoystick;
void virtual_joystick_cb(VirtualJoystick *w, void *data);

#endif
