// generated by Fast Light User Interface Designer (fluid) version 1.0500

#ifndef setup_ui_h
#define setup_ui_h
#include <FL/Fl.H>
#include "Fl_Console.hpp"
#include "Fl_DgFile.h"
#include "Fl_DgTable.h"
#include "Fl_PerfTable.h"
#include "Cgwin.hpp"
#include "essgui.h"
#include "EyeTouchWin.hpp"
#include "TclEditor.h"
#include "WheelSpinner.h"
#include "VirtualEye.hpp"
#include "VirtualJoystick.hpp"
#include "Fl_OpDesk.h"
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *main_window;
#include <FL/Fl_Menu_Bar.H>
extern Fl_Menu_Bar *menu_bar;
#include <FL/Fl_Tile.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Flex.H>
#include <FL/Fl_Button.H>
extern void refresh_cb(Fl_Button*, void*);
#include <FL/Fl_Output.H>
extern Fl_Output *sysname_widget;
extern Fl_Output *sysos_widget;
#include <FL/Fl_Tree.H>
extern void host_cb(Fl_Tree*, void*);
extern Fl_Tree *host_widget;
#include <FL/Fl_Choice.H>
extern Fl_Choice *subject_widget;
extern Fl_Output *system_status_widget;
extern Fl_Output *obscount_widget;
#include <FL/Fl_Box.H>
extern Fl_Box *obs_widget;
extern Fl_Choice *system_widget;
extern Fl_Choice *protocol_widget;
extern Fl_Choice *variant_widget;
#include <FL/Fl_Pack.H>
extern Fl_Pack *reload_buttons;
extern Fl_Button *reload_system_button;
extern Fl_Button *reload_protocol_button;
extern Fl_Button *reload_variant_button;
#include <FL/Fl_Scroll.H>
extern Fl_Scroll *options_widget;
extern Fl_Scroll *settings_widget;
#include <FL/Fl_Tabs.H>
extern EyeTouchWin *eyetouch_widget;
extern Fl_Output *eye_settings_label;
extern Fl_Flex *sorters_widget;
extern void sortby_cb(Fl_Choice*, void*);
extern Fl_Choice *sortby_1;
extern Fl_Choice *sortby_2;
extern PerfTable *perftable_widget;
extern PerfTable *general_perf_widget;
extern CGWin *plot_widget;
extern void virtual_eye_cb(VirtualEye*, void*);
extern VirtualEye *virtual_eye_widget;
extern void virtual_joystick_cb(VirtualJoystick*, void*);
extern VirtualJoystick *virtual_joystick_widget;
extern Wheel_Spinner *hBias_input;
extern Wheel_Spinner *vBias_input;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *hInvert_checkbox;
extern Fl_Check_Button *vInvert_checkbox;
extern Wheel_Spinner *hGain_input;
extern Wheel_Spinner *vGain_input;
extern Fl_Scroll *rmt_commands_widget;
extern DGTable *stimdg_widget;
extern void set_branch_cb(Fl_Choice*, void*);
extern Fl_Choice *branch_widget;
extern void save_script_cb(Fl_Button*, void*);
extern Fl_Button *save_script_button;
extern void push_script_cb(Fl_Button*, void*);
extern Fl_Button *push_script_button;
extern void pull_script_cb(Fl_Button*, void*);
extern Fl_Button *pull_script_button;
extern Fl_Tabs *editor_tabs;
extern TclEditor *system_editor;
extern TclEditor *protocol_editor;
extern TclEditor *loaders_editor;
extern TclEditor *variants_editor;
extern TclEditor *stim_editor;
extern Fl_OpDesk *opdesk_widget;
#include <FL/Fl_Input.H>
extern Fl_Input *FileEntry;
extern void file_open_cb(Fl_Button*, void*);
extern Fl_Button *FileOpen;
extern void file_close_cb(Fl_Button*, void*);
extern Fl_Button *FileClose;
extern void file_suggest_cb(Fl_Button*, void*);
extern Fl_Button *FileSuggest;
extern Fl_Console *output_term;
Fl_Double_Window * setup_ui(int argc, char *argv[]);
#endif
